version: '3.1'

services:

  bot:
    build: .
    restart: always
    ports:
      - '${PORT:-8000}:8000'
    entrypoint:
      - ./entrypoint.sh
    volumes:
      - ./data/logs:/usr/src/app/data/logs
    depends_on:
      - postgres
    environment:
      ADMINS: ${ADMINS}
      BOT_TOKEN: ${BOT_TOKEN}

      DATABASE_USER: postgres
      DATABASE_PASS: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432

      DATABASE_NAME: postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  postgres_backups:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - postgres_backups:/backups
    links:
      - postgres
    depends_on:
      - postgres
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
      - HEALTHCHECK_PORT=8080


volumes:
  postgres_data:
  postgres_backups:
